/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Memory;

import java.awt.Image;
import java.io.IOException;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author Gianluca
 */
public class Game extends javax.swing.JFrame {

    private final int N_CARTE = 16;
    private final Mazzo mazzo;
    
    private final ImageIcon[] icone;
    
    private Image logo;
    
    private final JButton[] pulsanti;
    
    private Boolean prima;
    private Boolean player1;
    private Boolean unLock;
    
    private Carta card1;
    private Carta card2;
    
    private int player1Score;
    private int player2Score;
    
    /**
     * Creates new form Game
     */
    public Game() {
        initComponents();
        
        this.player1 = true;
        this.prima = true;
        this.unLock = true;
        
        this.player1Score = 0;
        this.player2Score = 0;
        
        mazzo = new Mazzo (N_CARTE);
        
        icone = new ImageIcon[(N_CARTE / 2) + 1];
        genIcon();
        
        try {
            logo = ImageIO.read(getClass().getResource("/Memory/img/logo.png"));
        } catch (IOException ex) {
            Logger.getLogger(Game.class.getName()).log(Level.SEVERE, null, ex);
        }
        setIconImage(logo);
        
        pulsanti = new JButton[] {btnCard1, btnCard2, btnCard3, btnCard4, btnCard5, btnCard6, btnCard7, btnCard8, btnCard9, btnCard10, btnCard11, btnCard12, btnCard13, btnCard14, btnCard15, btnCard16};
    }
    
    private void genIcon() {
        int i;
        
        for(i = 0; i < (N_CARTE / 2) + 1; i++)
            icone[i] = new ImageIcon(getClass().getResource("/Memory/img/" + i + ".png"));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        btnCard1 = new javax.swing.JButton();
        btnCard2 = new javax.swing.JButton();
        btnCard3 = new javax.swing.JButton();
        btnCard4 = new javax.swing.JButton();
        btnCard5 = new javax.swing.JButton();
        btnCard6 = new javax.swing.JButton();
        btnCard7 = new javax.swing.JButton();
        btnCard8 = new javax.swing.JButton();
        btnCard9 = new javax.swing.JButton();
        btnCard10 = new javax.swing.JButton();
        btnCard11 = new javax.swing.JButton();
        btnCard12 = new javax.swing.JButton();
        btnCard13 = new javax.swing.JButton();
        btnCard14 = new javax.swing.JButton();
        btnCard15 = new javax.swing.JButton();
        btnCard16 = new javax.swing.JButton();
        lblPlayer2 = new javax.swing.JLabel();
        lblPlayer1 = new javax.swing.JLabel();
        lblTurno = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();
        lblEnd = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Memory");
        setIconImages(null);
        setResizable(false);

        btnCard1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btnCard1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Memory/img/8.png"))); // NOI18N
        btnCard1.setPreferredSize(new java.awt.Dimension(50, 50));
        btnCard1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCard1ActionPerformed(evt);
            }
        });

        btnCard2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btnCard2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Memory/img/8.png"))); // NOI18N
        btnCard2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCard2ActionPerformed(evt);
            }
        });

        btnCard3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btnCard3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Memory/img/8.png"))); // NOI18N
        btnCard3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCard3ActionPerformed(evt);
            }
        });

        btnCard4.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btnCard4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Memory/img/8.png"))); // NOI18N
        btnCard4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCard4ActionPerformed(evt);
            }
        });

        btnCard5.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btnCard5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Memory/img/8.png"))); // NOI18N
        btnCard5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCard5ActionPerformed(evt);
            }
        });

        btnCard6.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btnCard6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Memory/img/8.png"))); // NOI18N
        btnCard6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCard6ActionPerformed(evt);
            }
        });

        btnCard7.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btnCard7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Memory/img/8.png"))); // NOI18N
        btnCard7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCard7ActionPerformed(evt);
            }
        });

        btnCard8.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btnCard8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Memory/img/8.png"))); // NOI18N
        btnCard8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCard8ActionPerformed(evt);
            }
        });

        btnCard9.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btnCard9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Memory/img/8.png"))); // NOI18N
        btnCard9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCard9ActionPerformed(evt);
            }
        });

        btnCard10.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btnCard10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Memory/img/8.png"))); // NOI18N
        btnCard10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCard10ActionPerformed(evt);
            }
        });

        btnCard11.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btnCard11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Memory/img/8.png"))); // NOI18N
        btnCard11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCard11ActionPerformed(evt);
            }
        });

        btnCard12.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btnCard12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Memory/img/8.png"))); // NOI18N
        btnCard12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCard12ActionPerformed(evt);
            }
        });

        btnCard13.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btnCard13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Memory/img/8.png"))); // NOI18N
        btnCard13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCard13ActionPerformed(evt);
            }
        });

        btnCard14.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btnCard14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Memory/img/8.png"))); // NOI18N
        btnCard14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCard14ActionPerformed(evt);
            }
        });

        btnCard15.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btnCard15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Memory/img/8.png"))); // NOI18N
        btnCard15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCard15ActionPerformed(evt);
            }
        });

        btnCard16.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btnCard16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Memory/img/8.png"))); // NOI18N
        btnCard16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCard16ActionPerformed(evt);
            }
        });

        lblPlayer2.setText("PUNTEGGIO GIOCATORE 2: 0");

        lblPlayer1.setText("PUNTEGGIO GIOCATORE 1: 0");

        lblTurno.setForeground(new java.awt.Color(255, 0, 0));
        lblTurno.setText("TURNO GIOCATORE: 1");

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        lblEnd.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lblEnd.setForeground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPlayer2)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(lblTurno)
                        .addGap(18, 18, 18)
                        .addComponent(lblEnd))
                    .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(panelLayout.createSequentialGroup()
                            .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnCard1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnCard5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panelLayout.createSequentialGroup()
                                    .addComponent(btnCard6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnCard7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnCard8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panelLayout.createSequentialGroup()
                                    .addComponent(btnCard2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnCard3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnCard4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                            .addComponent(lblPlayer1)
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(btnReset))
                        .addGroup(panelLayout.createSequentialGroup()
                            .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelLayout.createSequentialGroup()
                                    .addComponent(btnCard13, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnCard14, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnCard15, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelLayout.createSequentialGroup()
                                    .addComponent(btnCard9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnCard10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnCard11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(18, 18, 18)
                            .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnCard12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnCard16, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCard1, btnCard10, btnCard11, btnCard12, btnCard13, btnCard14, btnCard15, btnCard16, btnCard2, btnCard3, btnCard4, btnCard5, btnCard6, btnCard7, btnCard8, btnCard9});

        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPlayer1)
                    .addComponent(btnReset))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPlayer2)
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTurno)
                    .addComponent(lblEnd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCard1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCard2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCard3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCard4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCard5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCard8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCard6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCard7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCard10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCard9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCard12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCard11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCard13, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCard16, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCard14, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCard15, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnCard1, btnCard10, btnCard11, btnCard12, btnCard13, btnCard14, btnCard15, btnCard16, btnCard2, btnCard3, btnCard4, btnCard5, btnCard6, btnCard7, btnCard8, btnCard9});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        System.out.println("");
        
        mazzo.reset();
        mazzo.genMazzo();
        
        this.player1Score = 0;
        this.player2Score = 0;
        
        this.prima = true;
        this.player1 = true;
        this.unLock = true;
        
        this.card1 = null;
        this.card2 = null;
        
        for(int i = 0; i < N_CARTE; i++){
            pulsanti[i].setEnabled(true);
            pulsanti[i].setIcon(icone[8]);
        }
        
        lblEnd.setText("");
        
        update();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnCard1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCard1ActionPerformed
        if(prima) {
            card1 = mazzo.cercaCarta(0);
            btnCard1.setIcon(icone[card1.getCode()]);
            prima = false;
        }
        else if (unLock && card1.getPos() != 0) {
            unLock = false;
            card2 = mazzo.cercaCarta(0);
            btnCard1.setIcon(icone[card2.getCode()]);
            if(card1.equals(card2)) {
                if(player1)
                    player1Score++;
                else
                    player2Score++;
                
                nascondi();
            }
            else {
                gira();
            }
        }
        
        update();
    }//GEN-LAST:event_btnCard1ActionPerformed

    private void btnCard4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCard4ActionPerformed
        if(prima) {
            card1 = mazzo.cercaCarta(3);
            btnCard4.setIcon(icone[card1.getCode()]);
            prima = false;
        }
        else if (unLock && card1.getPos() != 3) {
            unLock = false;
            card2 = mazzo.cercaCarta(3);
            btnCard4.setIcon(icone[card2.getCode()]);
            if(card1.equals(card2)) {
                if(player1)
                    player1Score++;
                else
                    player2Score++;
                
                nascondi();
            }
            else {
                gira();
            }
        }
        
        update();
    }//GEN-LAST:event_btnCard4ActionPerformed

    private void btnCard11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCard11ActionPerformed
        if(prima) {
            card1 = mazzo.cercaCarta(10);
            btnCard11.setIcon(icone[card1.getCode()]);
            prima = false;
        }
        else if (unLock && card1.getPos() != 10) {
            unLock = false;
            card2 = mazzo.cercaCarta(10);
            btnCard11.setIcon(icone[card2.getCode()]);
            if(card1.equals(card2)) {
                if(player1)
                    player1Score++;
                else
                    player2Score++;
                
                nascondi();
            }
            else {
                gira();
            }
        }
        
        update();
    }//GEN-LAST:event_btnCard11ActionPerformed

    private void btnCard2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCard2ActionPerformed
        if(prima) {
            card1 = mazzo.cercaCarta(1);
            btnCard2.setIcon(icone[card1.getCode()]);
            prima = false;
        }
        else if (unLock && card1.getPos() != 1) {
            unLock = false;
            card2 = mazzo.cercaCarta(1);
            btnCard2.setIcon(icone[card2.getCode()]);
            if(card1.equals(card2)) {
                if(player1)
                    player1Score++;
                else
                    player2Score++;
                
                nascondi();
            }
            else {
                gira();
            }
        }
        
        update();
    }//GEN-LAST:event_btnCard2ActionPerformed

    private void btnCard3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCard3ActionPerformed
        if(prima) {
            card1 = mazzo.cercaCarta(2);
            btnCard3.setIcon(icone[card1.getCode()]);
            prima = false;
        }
        else if (unLock && card1.getPos() != 2) {
            unLock = false;
            card2 = mazzo.cercaCarta(2);
            btnCard3.setIcon(icone[card2.getCode()]);
            if(card1.equals(card2)) {
                if(player1)
                    player1Score++;
                else
                    player2Score++;
                
                nascondi();
            }
            else {
                gira();
            }
        }
        
        update();
    }//GEN-LAST:event_btnCard3ActionPerformed

    private void btnCard5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCard5ActionPerformed
        if(prima) {
            card1 = mazzo.cercaCarta(4);
            btnCard5.setIcon(icone[card1.getCode()]);
            prima = false;
        }
        else if (unLock && card1.getPos() != 4) {
            unLock = false;
            card2 = mazzo.cercaCarta(4);
            btnCard5.setIcon(icone[card2.getCode()]);
            if(card1.equals(card2)) {
                if(player1)
                    player1Score++;
                else
                    player2Score++;
                
                nascondi();
            }
            else {
                gira();
            }
        }
        
        update();
    }//GEN-LAST:event_btnCard5ActionPerformed

    private void btnCard6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCard6ActionPerformed
        if(prima) {
            card1 = mazzo.cercaCarta(5);
            btnCard6.setIcon(icone[card1.getCode()]);
            prima = false;
        }
        else if (unLock && card1.getPos() != 5) {
            unLock = false;
            card2 = mazzo.cercaCarta(5);
            btnCard6.setIcon(icone[card2.getCode()]);
            if(card1.equals(card2)) {
                if(player1)
                    player1Score++;
                else
                    player2Score++;
                
                nascondi();
            }
            else {
                gira();
            }
        }
        
        update();
    }//GEN-LAST:event_btnCard6ActionPerformed

    private void btnCard7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCard7ActionPerformed
        if(prima) {
            card1 = mazzo.cercaCarta(6);
            btnCard7.setIcon(icone[card1.getCode()]);
            prima = false;
        }
        else if (unLock && card1.getPos() != 6) {
            unLock = false;
            card2 = mazzo.cercaCarta(6);
            btnCard7.setIcon(icone[card2.getCode()]);
            if(card1.equals(card2)) {
                if(player1)
                    player1Score++;
                else
                    player2Score++;
                
                nascondi();
            }
            else {
                gira();
            }
        }
        
        update();
    }//GEN-LAST:event_btnCard7ActionPerformed

    private void btnCard8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCard8ActionPerformed
        if(prima) {
            card1 = mazzo.cercaCarta(7);
            btnCard8.setIcon(icone[card1.getCode()]);
            prima = false;
        }
        else if (unLock && card1.getPos() != 7) {
            unLock = false;
            card2 = mazzo.cercaCarta(7);
            btnCard8.setIcon(icone[card2.getCode()]);
            if(card1.equals(card2)) {
                if(player1)
                    player1Score++;
                else
                    player2Score++;
                
                nascondi();
            }
            else {
                gira();
            }
        }
        
        update();
    }//GEN-LAST:event_btnCard8ActionPerformed

    private void btnCard9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCard9ActionPerformed
        if(prima) {
            card1 = mazzo.cercaCarta(8);
            btnCard9.setIcon(icone[card1.getCode()]);
            prima = false;
        }
        else if (unLock && card1.getPos() != 8) {
            unLock = false;
            card2 = mazzo.cercaCarta(8);
            btnCard9.setIcon(icone[card2.getCode()]);
            if(card1.equals(card2)) {
                if(player1)
                    player1Score++;
                else
                    player2Score++;
                
                nascondi();
            }
            else {
                gira();
            }
        }
        
        update();
    }//GEN-LAST:event_btnCard9ActionPerformed

    private void btnCard10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCard10ActionPerformed
        if(prima) {
            card1 = mazzo.cercaCarta(9);
            btnCard10.setIcon(icone[card1.getCode()]);
            prima = false;
        }
        else if (unLock && card1.getPos() != 9) {
            unLock = false;
            card2 = mazzo.cercaCarta(9);
            btnCard10.setIcon(icone[card2.getCode()]);
            if(card1.equals(card2)) {
                if(player1)
                    player1Score++;
                else
                    player2Score++;
                
                nascondi();
            }
            else {
                gira();
            }
        }
        
        update();
    }//GEN-LAST:event_btnCard10ActionPerformed

    private void btnCard12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCard12ActionPerformed
        if(prima) {
            card1 = mazzo.cercaCarta(11);
            btnCard12.setIcon(icone[card1.getCode()]);
            prima = false;
        }
        else if (unLock && card1.getPos() != 11) {
            unLock = false;
            card2 = mazzo.cercaCarta(11);
            btnCard12.setIcon(icone[card2.getCode()]);
            if(card1.equals(card2)) {
                if(player1)
                    player1Score++;
                else
                    player2Score++;
                
                nascondi();
            }
            else {
                gira();
            }
        }
        
        update();
    }//GEN-LAST:event_btnCard12ActionPerformed

    private void btnCard13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCard13ActionPerformed
        if(prima) {
            card1 = mazzo.cercaCarta(12);
            btnCard13.setIcon(icone[card1.getCode()]);
            prima = false;
        }
        else if (unLock && card1.getPos() != 12) {
            unLock = false;
            card2 = mazzo.cercaCarta(12);
            btnCard13.setIcon(icone[card2.getCode()]);
            if(card1.equals(card2)) {
                if(player1)
                    player1Score++;
                else
                    player2Score++;
                
                nascondi();
            }
            else {
                gira();
            }
        }
        
        update();
    }//GEN-LAST:event_btnCard13ActionPerformed

    private void btnCard14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCard14ActionPerformed
        if(prima) {
            card1 = mazzo.cercaCarta(13);
            btnCard14.setIcon(icone[card1.getCode()]);
            prima = false;
        }
        else if (unLock && card1.getPos() != 13) {
            unLock = false;
            card2 = mazzo.cercaCarta(13);
            btnCard14.setIcon(icone[card2.getCode()]);
            if(card1.equals(card2)) {
                if(player1)
                    player1Score++;
                else
                    player2Score++;
                
                nascondi();
            }
            else {
                gira();
            }
        }
        
        update();
    }//GEN-LAST:event_btnCard14ActionPerformed

    private void btnCard15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCard15ActionPerformed
        if(prima) {
            card1 = mazzo.cercaCarta(14);
            btnCard15.setIcon(icone[card1.getCode()]);
            prima = false;
        }
        else if (unLock && card1.getPos() != 14) {
            unLock = false;
            card2 = mazzo.cercaCarta(14);
            btnCard15.setIcon(icone[card2.getCode()]);
            if(card1.equals(card2)) {
                if(player1)
                    player1Score++;
                else
                    player2Score++;
                
                nascondi();
            }
            else {
                gira();
            }
        }
        
        update();
    }//GEN-LAST:event_btnCard15ActionPerformed

    private void btnCard16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCard16ActionPerformed
        if(prima) {
            card1 = mazzo.cercaCarta(15);
            btnCard16.setIcon(icone[card1.getCode()]);
            prima = false;
        }
        else if (unLock && card1.getPos() != 15) {
            unLock = false;
            card2 = mazzo.cercaCarta(15);
            btnCard16.setIcon(icone[card2.getCode()]);
            if(card1.equals(card2)) {
                if(player1)
                    player1Score++;
                else
                    player2Score++;
                
                nascondi();
            }
            else {
                gira();
            }
        }
        
        update();
    }//GEN-LAST:event_btnCard16ActionPerformed

    public void nascondi () {
        pulsanti[card1.getPos()].setEnabled(false);
        pulsanti[card2.getPos()].setEnabled(false);
        
        card1 = null;
        card2 = null;

        unLock = true;
        prima = true;
        
        if(player1Score + player2Score != 8)
            update();
    }
    
    public void gira () {
        Timer timer = new Timer();
        timer.schedule(new TimerTask() {
            @Override
            public void run(){
                pulsanti[card1.getPos()].setIcon(icone[8]);
                pulsanti[card2.getPos()].setIcon(icone[8]);
                
                card1 = null;
                card2 = null;
                player1 = !player1;
                
                update();
                
                timer.cancel();
                
                unLock = true;
                prima = true;
            }
        }, 3000);
    }
    
    public void update () {
        if(player1Score + player2Score == 8){
            if(player1Score > player2Score){
                lblPlayer1.setText("PUNTEGGIO GIOCATORE 1: WINNER WINNER CHICKEN DINNER");
                JOptionPane.showMessageDialog(rootPane, "Il giocatore 1 ha vinto!");
            }
            else {
                lblPlayer2.setText("PUNTEGGIO GIOCATORE 2: WINNER WINNER CHICKEN DINNER");
                JOptionPane.showMessageDialog(rootPane, "Il giocatore 2 ha vinto!");
            }
            
            lblEnd.setText("Premi 'reset' per ricominciare!");
        }
        else {
            lblPlayer1.setText("PUNTEGGIO GIOCATORE 1: " + player1Score);
            lblPlayer2.setText("PUNTEGGIO GIOCATORE 2: " + player2Score);
        }
            
        if(player1)
            lblTurno.setText("TURNO GIOCATORE: 1");
        else
            lblTurno.setText("TURNO GIOCATORE: 2");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Game().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCard1;
    private javax.swing.JButton btnCard10;
    private javax.swing.JButton btnCard11;
    private javax.swing.JButton btnCard12;
    private javax.swing.JButton btnCard13;
    private javax.swing.JButton btnCard14;
    private javax.swing.JButton btnCard15;
    private javax.swing.JButton btnCard16;
    private javax.swing.JButton btnCard2;
    private javax.swing.JButton btnCard3;
    private javax.swing.JButton btnCard4;
    private javax.swing.JButton btnCard5;
    private javax.swing.JButton btnCard6;
    private javax.swing.JButton btnCard7;
    private javax.swing.JButton btnCard8;
    private javax.swing.JButton btnCard9;
    private javax.swing.JButton btnReset;
    private javax.swing.JLabel lblEnd;
    private javax.swing.JLabel lblPlayer1;
    private javax.swing.JLabel lblPlayer2;
    private javax.swing.JLabel lblTurno;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
}
